amd:
  - я купил амд и не пожалел, продал амд и еще раз куплю амд
  - ох, как хочется взять 4.2 на 2600
  - ты опять ебанулся, уже считали аналогичную сборку не 2011, амд вышло дешевле
  - ну да, 3200 за его цену оч хорошо заходит и даже доп питание на вк не нужно
  - https://clck.ru/H2YpF не сливайте пока никуда вне чата, 2600 - за 3.6к 
  - кстати, я уже заказл 2600+б450-а+баллистики, вышло 20к, сегодня проц забираю, в субботу мать и озу
бургер:
  - в смысле фотка горца? я ненавижу бк, лол
  - я ненавижу бк, сорян 
  - "> весь разговор шёл про пиццу > ря, бургер, ря"
  - ну что, 36 наггетсов?
  - оо, ну за наггетсы в маке я готов отдать 3 сотни спокойно, ибо они очень годные
  - ну да, в бк не наггетсы, а просто позор
рашк:
  - я тебе дал пример нарушения, а ты говоришь, что у других такое же, это как-то оправдывает рашку?
  - я - патриот, врети
  - алсо, резко кол-во айфонов упадёт, ибо заказать вне рашки не смогут
  - #полицейское госво as is, хуже и быть не может
  - зачем ты берешь другую страну, когда мы говорим только про рашку?
  - смотри, есть гражданин рашки и пидораха, здесь тоже самое, ну аналогично)
  - ну естественно, что речь идёт про нормальную трактовку, а не про рашкинскую
  - патриот, плес, посмотри уровень жизни у среднего гражданина стран ес
  - ря, у нас и конституция есть, только она не работает
  - "@approachingnirvana @Spiege1 нарушается ли конституция в нашей стране?"
пицц:
  - "@day_forum, там это, роллы подвезли от Никиты, если надо"
  - дока пицца получше будет, там 9 пицц за 1.5к
  - у тебя есть вариант взять много вкусной пиццы за очень хорошую цену, но тебе придётся похавать пиццу еще 2 дня, её можно греть, ты бы не взял)? 
  - я больше 2 дней не храню пиццу, правда бесплатные биг тейсти в колве 50 штук на балконе лежали, я их в итоге за 3-4 дня схавал)
kfc:
  - ты читать научись, мы все это время говорили про пиццы 
  - 3870 топовый купон кстати)
  - узнаю 3870 из тысячи
  - голодающие тут?
  - это я перед ивентом зашёл, после ивента 3870
  - говно или нет зато недорого
  - самый выгодный по соотношению цены/сытности, в данный момент - боксмастер+напиток+картофель за 184
  - ведра в кфс очень годные, я даже железное купил, чтоб скидка в 30% была на год
  - можно только крылья (сейчас апнули до 30 шт в 1 ведре, годнота)
  - ну мне нравится в стрипсах, что они очень хорошо идут и нет кости внутри, как семечки
  - https://www.kfc.ru/foodorder/product/1256
срач:
  - ну ты это не мне присылай, а тем, кто начал
  - ничего нового
  - хуйню опять финик начал говорить, без пруфов, ничего нового
  - ты не чекаешь весь чат и делаешь неправильные выводы
  - и да, зачем все это, опять не понимаю смысла этой дискуссии
  - заметь, опять начал не я)
  - почему вам так сложно принять мои взгляды?
  - уже давно срач, очень давно
горец:
  - нет, ты ошибаешься
  - не реагирую на такое и не буду
  - это я уже могу сам решить, без тебя, спасибо
  - ты считаешь, что можешь указывать кому-то на то, что он не прав, а потом говорить 'ну ты не прав кароч' и нормально после этого общаться?
  - я уже не горец
  - блудный горец
  - ты даже не прочёл, но уже делаешь вывод
клав:
  - а как потом клаву чистить?
  - спроси у Кости)
  - "клава на чёрных свичах норм? @Gittorian"
  - да, сложно конкуренцию ебашить, если мембранка тупо по комплектующим на порядок дешевле
  - надо просто цену уменьшить, и тогда люди будут брать механику, весь вопрос в цене и доступности
